---
# Variables listed here are applicable to "setup" roles

# Remote host variables
hostname: appserver
host_distribution_release: bionic
appserver_username: ubuntu
deploy_username: devTeam

# User admin variables
admin_username: ribbo
admin_password: sbalbu

# Miscellaneous variables
docker_group: docker