# This playbook contains tasks related to the basic setup of the server

# Install all base packages needed
- name: Install base packages
  apt: 
    name: ['locales', 'build-essential', 'acl', 'ntp', 'htop', 'git', 'supervisor', 'python-pip', 'python3-pip', 'nginx' ]
    state: present
  tags:
    - packages

# Upgrade pip package
- name: Upgrade pip
  pip:
    name: pip
    state: latest
  tags:
    - packages
